### ISSUE TITLE
Arrow functions

### ISSUE THREAD

**Issue by r00bal** [KamilSzafranski/goit-react-hw-02-phonebook#1]
https://github.com/KamilSzafranski/goit-react-hw-02-phonebook/blob/7a310af4843c8c875acb696c1791f838e2231586/src/components/App.jsx#L18-L24

Można skrócić do

```
 renderFilteredData = () =>
    this.state.contacts.filter(element =>
      element.name.toLowerCase().startsWith(this.state.filter.toLowerCase())
    );
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by KamilSzafranski** [comment]
Poprawione
